//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL_business_object_layer_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebAppEntities : DbContext
    {
        public WebAppEntities()
            : base("name=WebAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_category> tbl_category { get; set; }
        public virtual DbSet<tbl_city> tbl_city { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
        public virtual DbSet<tbl_ContactUs> tbl_ContactUs { get; set; }
        public virtual DbSet<tbl_Admin> tbl_Admin { get; set; }
        public virtual DbSet<tbl_Packages> tbl_Packages { get; set; }
        public virtual DbSet<tbl_MakeMyTrip> tbl_MakeMyTrip { get; set; }
        public virtual DbSet<tbl_MemberShip> tbl_MemberShip { get; set; }
        public virtual DbSet<tbl_Guide> tbl_Guide { get; set; }
        public virtual DbSet<tbl_Hotel_images> tbl_Hotel_images { get; set; }
        public virtual DbSet<tbl_Hotels> tbl_Hotels { get; set; }
    }
}
