//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL_business_object_layer_
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MemberShip
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Price { get; set; }
        public string Monthly_Cost { get; set; }
        public string Monthly_Souvenirs { get; set; }
        public string Trekking_Equipment { get; set; }
        public string Extra_Field1 { get; set; }
        public string Extra_Field2 { get; set; }
    }
}
